# Example override file. Copy as docker-compose.override.yml and edit as needed

# Please note that when defining lists here, they will be merged with the
# lists in the base file. If you want to completely override a list, instead
# you need to use the special syntax "!override" and "!reset".
# For more details: https://docs.docker.com/reference/compose-file/merge/

services:
  web:
    volumes:  !override
      # {YOUR_STATIC_PATH}:/home/wger/static
      # {YOUR_MEDIA_PATH}:/home/wger/media
      - /mnt/glop/wger-data/static:/home/wger/static
      - /mnt/glop/wger-data/media:/home/wger/media
  
  celery_worker:
    volumes:  !override
      # {YOUR_MEDIA_PATH}:/home/wger/media
      - /mnt/glop/wger-data/media:/home/wger/media

  celery_beat:
    volumes:  !override
      # {YOUR_BEAT_PATH}:/home/wger/beat
      - /mnt/glop/wger-data/beat:/home/wger/beat/

  nginx:
    ports:    !override
      # {hostPort}:80 --- TrueNAS defaults to 30170 as web access port. Nginx conf file uses 80 as listening port -  don't change.
      - "30170:80"

    volumes:  !override
      # {YOUR_STATIC_PATH}:/wger/static:ro
      # {YOUR_MEDIA_PATH}:/wger/media:ro
      - /mnt/glop/wger-data/static:/wger/static:ro
      - /mnt/glop/wger-data/media:/wger/media:ro

      # Don't touch this line
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf      

  db:
    image: docker.io/postgres:18.4-trixie
    volumes:  !override
      #  {YOUR_DATABASE_PATH}:/var/lib/postgresql/data
      - /mnt/glop/wger-data/pgdata:/var/lib/postgresql/data